SELECT A.GIROTYP, A.ANSLUTNINGSID, B.FAKTKTO, A.ANSLUT_DATUM, A.AVSLUT_DATUM, A.PERSONNR, A.STATUSKOD, A.BEVAK_MARKERING, A.MEDDELANDE_MARK, A.LEV_SYSTEM, DATE('9999-12-31') AS CONN_HIST_DATE,  DATE('9999-12-31') AS BACT_HIST_DATE  FROM  STHDSN6.TENA2.FGT0200  B, STHDSN6.TENA2.FGT0100 A WHERE B.ANSLUTNINGSID = A.ANSLUTNINGSID AND A.ANSLUTNINGSID =:ANSLUTNINGSID UNION SELECT C.GIROTYP, C.ANSLUTNINGSID, D.FAKTKTO, C.ANSLUT_DATUM, C.AVSLUT_DATUM, C.PERSONNR, C.STATUSKOD, C.BEVAK_MARKERING, C.MEDDELANDE_MARK, C.LEV_SYSTEM, DATE(C.HIST_DATUM) AS CONN_HIST_DATE,  DATE(D.UPPLDAT) AS BACT_HIST_DATE FROM  STHDSN6.TENA2.FGT1000 D, STHDSN6.TENA2.FGT0900 C WHERE D.ANSLUTNINGSID = C.ANSLUTNINGSID AND C.ANSLUTNINGSID =:ANSLUTNINGSID



{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.GIROTYP, A.ANSLUTNINGSID, B.FAKTKTO, A.ANSLUT_DATUM, A.AVSLUT_DATUM, A.PERSONNR, A.STATUSKOD, A.BEVAK_MARKERING, A.MEDDELANDE_MARK, A.LEV_SYSTEM, DATE('9999-12-31') AS CONN_HIST_DATE,  DATE('9999-12-31') AS BACT_HIST_DATE  FROM  STHDSN6.TENA2.FGT0200  B, STHDSN6.TENA2.FGT0100 A WHERE B.ANSLUTNINGSID = A.ANSLUTNINGSID AND A.ANSLUTNINGSID =:ANSLUTNINGSID UNION SELECT C.GIROTYP, C.ANSLUTNINGSID, D.FAKTKTO, C.ANSLUT_DATUM, C.AVSLUT_DATUM, C.PERSONNR, C.STATUSKOD, C.BEVAK_MARKERING, C.MEDDELANDE_MARK, C.LEV_SYSTEM, DATE(C.HIST_DATUM) AS CONN_HIST_DATE,  DATE(D.UPPLDAT) AS BACT_HIST_DATE FROM  STHDSN6.TENA2.FGT1000 D, STHDSN6.TENA2.FGT0900 C WHERE D.ANSLUTNINGSID = C.ANSLUTNINGSID AND C.ANSLUTNINGSID =:ANSLUTNINGSID",
  "serviceName": "auto04",
  "description": "auto04 based on ANSLUTNINGSID.",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}


curl -X 'POST'  \
'http://131.116.44.144:1316/services/DB2ServiceManager'  \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
"requestType": "createService",
"sqlStmt": "SELECT A.GIROTYP, A.ANSLUTNINGSID, B.FAKTKTO, A.ANSLUT_DATUM, A.AVSLUT_DATUM, A.PERSONNR, A.STATUSKOD, A.BEVAK_MARKERING, A.MEDDELANDE_MARK, A.LEV_SYSTEM, DATE('9999-12-31') AS CONN_HIST_DATE,  DATE('9999-12-31') AS BACT_HIST_DATE  FROM  STHDSN6.TENA2.FGT0200  B, STHDSN6.TENA2.FGT0100 A WHERE B.ANSLUTNINGSID = A.ANSLUTNINGSID AND A.ANSLUTNINGSID =:ANSLUTNINGSID UNION SELECT C.GIROTYP, C.ANSLUTNINGSID, D.FAKTKTO, C.ANSLUT_DATUM, C.AVSLUT_DATUM, C.PERSONNR, C.STATUSKOD, C.BEVAK_MARKERING, C.MEDDELANDE_MARK, C.LEV_SYSTEM, DATE(C.HIST_DATUM) AS CONN_HIST_DATE,  DATE(D.UPPLDAT) AS BACT_HIST_DATE FROM  STHDSN6.TENA2.FGT1000 D, STHDSN6.TENA2.FGT0900 C WHERE D.ANSLUTNINGSID = C.ANSLUTNINGSID AND C.ANSLUTNINGSID =:ANSLUTNINGSID",
"serviceName": "auto04",
"description": "auto04 based on  ANSLUTNINGSID"
}'





curl -X GET http://131.116.44.144:1316/services/SYSIBMSERVICE/auto04/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq
