SELECT A.GIROTYP, A.ANSLUTNINGSID, A.ANSLUT_DATUM, A.AVSLUT_DATUM, A.PERSONNR, A.STATUSKOD, A.BEVAK_MARKERING, A.MEDDELANDE_MARK, A.LEV_SYSTEM, DATE('9999-12-31') AS CONN_HIST_DATE, B.FAKTKTO, DATE('9999-12-31') AS BACT_HIST_DATE FROM  TENA2.FGT0100 A LEFT JOIN TENA2.FGT0200  B ON B.ANSLUTNINGSID = A.ANSLUTNINGSID WHERE  A.ANSLUTNINGSID =:ANSLUTNINGSID UNION SELECT C.GIROTYP, C.ANSLUTNINGSID, C.ANSLUT_DATUM, C.AVSLUT_DATUM, C.PERSONNR, C.STATUSKOD, C.BEVAK_MARKERING, C.MEDDELANDE_MARK, C.LEV_SYSTEM, DATE(C.HIST_DATUM) AS CONN_HIST_DATE, D.FAKTKTO, DATE(D.UPPLDAT) AS BACT_HIST_DATE FROM  TENA2.FGT0900 C LEFT JOIN TENA2.FGT1000 D ON D.ANSLUTNINGSID = C.ANSLUTNINGSID WHERE  C.ANSLUTNINGSID =:ANSLUTNINGSID

{
  "dburl": "http://131.116.44.144:1316/services/SYSIBMSERVICE/test/V1",
  "username": "a472inb",
  "password": "INblatS2",
  "params": {
   "ANSLUTNINGSID": "000000000001558030"
  },
  "response": ""
}

curl -X POST \
http://131.116.44.144:1316/services/SYSIBMSERVICE/test/V1 \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
 "ANSLUTNINGSID": "000000000001558030"
}'


curl -X GET http://131.116.44.144:1316/services/SYSIBMSERVICE/test/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq
{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.GIROTYP, A.ANSLUTNINGSID, A.ANSLUT_DATUM, A.AVSLUT_DATUM, A.PERSONNR, A.STATUSKOD, A.BEVAK_MARKERING, A.MEDDELANDE_MARK, A.LEV_SYSTEM, DATE('9999-12-31') AS CONN_HIST_DATE, B.FAKTKTO, DATE('9999-12-31') AS BACT_HIST_DATE FROM  TENA2.FGT0100 A LEFT JOIN TENA2.FGT0200  B ON B.ANSLUTNINGSID = A.ANSLUTNINGSID WHERE  A.ANSLUTNINGSID =:ANSLUTNINGSID UNION SELECT C.GIROTYP, C.ANSLUTNINGSID, C.ANSLUT_DATUM, C.AVSLUT_DATUM, C.PERSONNR, C.STATUSKOD, C.BEVAK_MARKERING, C.MEDDELANDE_MARK, C.LEV_SYSTEM, DATE(C.HIST_DATUM) AS CONN_HIST_DATE, D.FAKTKTO, DATE(D.UPPLDAT) AS BACT_HIST_DATE FROM  TENA2.FGT0900 C LEFT JOIN TENA2.FGT1000 D ON D.ANSLUTNINGSID = C.ANSLUTNINGSID WHERE  C.ANSLUTNINGSID =:ANSLUTNINGSID",
  "serviceName": "test",
  "description": "test based on ANSLUTNINGSID.",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}


curl -X 'POST'  \
'http://131.116.44.144:1316/services/DB2ServiceManager'  \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
"requestType": "createService",
"sqlStmt": "SELECT A.GIROTYP, A.ANSLUTNINGSID, A.ANSLUT_DATUM, A.AVSLUT_DATUM, A.PERSONNR, A.STATUSKOD, A.BEVAK_MARKERING, A.MEDDELANDE_MARK, A.LEV_SYSTEM, DATE('9999-12-31') AS CONN_HIST_DATE, B.FAKTKTO, DATE('9999-12-31') AS BACT_HIST_DATE FROM  TENA2.FGT0100 A LEFT JOIN TENA2.FGT0200  B ON B.ANSLUTNINGSID = A.ANSLUTNINGSID WHERE  A.ANSLUTNINGSID =:ANSLUTNINGSID UNION SELECT C.GIROTYP, C.ANSLUTNINGSID, C.ANSLUT_DATUM, C.AVSLUT_DATUM, C.PERSONNR, C.STATUSKOD, C.BEVAK_MARKERING, C.MEDDELANDE_MARK, C.LEV_SYSTEM, DATE(C.HIST_DATUM) AS CONN_HIST_DATE, D.FAKTKTO, DATE(D.UPPLDAT) AS BACT_HIST_DATE FROM  TENA2.FGT0900 C LEFT JOIN TENA2.FGT1000 D ON D.ANSLUTNINGSID = C.ANSLUTNINGSID WHERE  C.ANSLUTNINGSID =:ANSLUTNINGSID",
"serviceName": "test",
"description": "test based on  ANSLUTNINGSID"
}'