{
  "dburl": "http://131.116.44.150:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":" SELECT     C.CURR_BACCT_ID, C.BACCT_OID, A.INTVL_START_DATE, A.GDRL_ENT_OID, A.GDRL_CMPNT_SQNM, CAST(A.GDRL_LVL_USE_IND AS VARCHAR(8) FOR SBCS DATA) AS GDRL_LVL_USE_IND, B.CURR_CNUM_ID, C.BACCT_PARTN_ID FROM       STHDSN1.TICGRP1.GUIDE_RULE_DATA A, STHDSN1.TICGRP1.CNUM_DATA B, STHDSN1.TICGRP1.BACCT_DATA C, STHDSN1.TICGRP1.CNUM_HIST_DATA D WHERE      A.BACCT_OID =:BACCT_OID AND A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND A.RLTD_INSTN_OID =:RLTD_INSTN_OID AND        D.CURR_CUST_PARTN_ID = A.RLTD_CUST_PARTN_ID AND        D.CNUM_OID = A.RLTD_CNUM_OID AND        D.INTVL_START_DATE = (SELECT  MAX(INTVL_START_DATE) FROM       STHDSN1.TICGRP1.CNUM_HIST_DATA WHERE   CURR_CUST_PARTN_ID = D.CURR_CUST_PARTN_ID AND     CNUM_OID = D.CNUM_OID) AND       (D.OWN_CNUM_OID = 0 OR   D.OWN_CNUM_OID = D.CNUM_OID OR NOT EXISTS (SELECT * FROM    STHDSN1.TICGRP1.GUIDE_RULE_DATA WHERE   GDRL_ENT_OID = D.OWN_CNUM_OID AND     BACCT_OID = A.BACCT_OID)) AND        C.BACCT_PARTN_ID = A.BACCT_PARTN_ID AND        C.BACCT_OID = A.BACCT_OID AND        B.CURR_CUST_PARTN_ID = A.RLTD_CUST_PARTN_ID AND        B.CNUM_OID = A.RLTD_CNUM_OID ORDER BY B.CURR_CNUM_ID, A.INTVL_START_DATE DESC, A.GDRL_CMPNT_SQNM ",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "kfs03b",
  "description": "kfs03b BACCT_OID,BACCT_PARTN_ID,RLTD_INSTN_OID",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}
