ovr_avs0842



SELECT A.BLLITM_DATE, A.RLTD_INSTN_OID, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(14) FOR SBCS DATA) AS BLLITM_ID, A.ACTV_INACTV_IND FROM STHDSN1.TICGRP1.MISC_BLLITM_DATA A WHERE A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND A.BACCT_OID =:BACCT_OID AND CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA) =:TCOMITM_CAT_COD AND A.RLTD_CNUM_OID =:RLTD_CNUM_OID AND A.BLLITM_TYP_IND = 'M' AND SUBSTR(A.MSG_LINE_TXT,1,250) =:MSG_LINE_TXT ORDER BY  5,1 desc

		
{
  "dburl": "http://131.116.44.152:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.BLLITM_DATE, A.RLTD_INSTN_OID, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(14) FOR SBCS DATA) AS BLLITM_ID, A.ACTV_INACTV_IND FROM STHDSN1.TICGRP1.MISC_BLLITM_DATA A WHERE A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND A.BACCT_OID =:BACCT_OID AND CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA) =:TCOMITM_CAT_COD AND A.RLTD_CNUM_OID =:RLTD_CNUM_OID AND A.BLLITM_TYP_IND = 'M' AND SUBSTR(A.MSG_LINE_TXT,1,250) =:MSG_LINE_TXT ORDER BY  5,1 desc",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "ovr_avs0842",
  "owner": "COMINAT5",
   "validate": "BIND",
  "description": "ovr_avs0842 based on BACCT_PARTN_ID,BACCT_OID ,TCOMITM_CAT_COD,RLTD_CNUM_OID and MSG_LINE_TXT ",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}
curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/ovr_avs0842/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq




