SELECT        A.BLLITM_STRTDT, A.BLLITM_STOPDT, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(14) FOR SBCS DATA) AS BLLITM_ID FROM         STHDSN1.TICGRP1.RECUR_ITEM_DATA A, STHDSN1.TICGRP1.CNUM_DATA B, STHDSN1.TICGRP1.RECUR_ITM_HST_DATA C WHERE         A.CURR_BACCT_OID =:CURR_BACCT_OID AND          CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA)  =:TCOMITM_CAT_COD AND           A.RLTD_INSTN_OID =:RLTD_INSTN_OID AND           B.CURR_CUST_PARTN_ID = A.RLTD_CUST_PARTN_ID AND           B.CNUM_OID = A.RLTD_CNUM_OID AND           B.CURR_CNUM_ID =:CURR_CNUM_ID AND           A.BLLITM_STOPDT = '9999-12-31' AND           C.BACCT_PARTN_ID = A.BACCT_PARTN_ID AND           C.BLLITM_OID = A.BLLITM_OID AND           SUBSTR(C.MSG_LINE_TXT,1,250) = ' ' AND           C.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM   STHDSN1.TICGRP1.RECUR_ITM_HST_DATA WHERE   BACCT_PARTN_ID = A.BACCT_PARTN_ID AND     BLLITM_OID = A.BLLITM_OID AND  SUBSTR(MSG_LINE_TXT,1,250) = ' ') ORDER BY 2 DESC, 1, 4



{
  "dburl": "http://131.116.44.152:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":"SELECT        A.BLLITM_STRTDT, A.BLLITM_STOPDT, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(14) FOR SBCS DATA) AS BLLITM_ID FROM         STHDSN1.TICGRP1.RECUR_ITEM_DATA A, STHDSN1.TICGRP1.CNUM_DATA B, STHDSN1.TICGRP1.RECUR_ITM_HST_DATA C WHERE         A.CURR_BACCT_OID =:CURR_BACCT_OID AND          CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA)  =:TCOMITM_CAT_COD AND           A.RLTD_INSTN_OID =:RLTD_INSTN_OID AND           B.CURR_CUST_PARTN_ID = A.RLTD_CUST_PARTN_ID AND           B.CNUM_OID = A.RLTD_CNUM_OID AND           B.CURR_CNUM_ID =:CURR_CNUM_ID AND           A.BLLITM_STOPDT = '9999-12-31' AND           C.BACCT_PARTN_ID = A.BACCT_PARTN_ID AND           C.BLLITM_OID = A.BLLITM_OID AND           SUBSTR(C.MSG_LINE_TXT,1,250) = ' ' AND           C.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM   STHDSN1.TICGRP1.RECUR_ITM_HST_DATA WHERE   BACCT_PARTN_ID = A.BACCT_PARTN_ID AND     BLLITM_OID = A.BLLITM_OID AND  SUBSTR(MSG_LINE_TXT,1,250) = ' ') ORDER BY 2 DESC, 1, 4",
  "serviceName": "per_avs081",
  "description": "per_avs081 based on BACCT_PARTN_ID,BACCT_OID ,TCOMITM_CAT_COD",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}


curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/per_avs081/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq


curl -X POST \
http://131.116.44.152:1317/services/SYSIBMSERVICE/per_avs081/V1 \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
    "CURR_BACCT_OID": "4675438",
    "RLTD_CNUM_OID": "11912254",
    "RLTD_INSTN_OID": "82091815",
    "TCOMITM_CAT_COD": "00025106"
}'