{
  "dburl": "http://131.116.44.152:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":"SELECT A.BLLITM_STRTDT, A.BLLITM_STOPDT, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(32) FOR SBCS DATA) AS BLLITM_ID FROM STHDSN1.TICGRP1.RECUR_ITEM_DATA A,STHDSN1.TICGRP1.RECUR_ITM_HST_DATA B WHERE A.CURR_BACCT_OID=:CURR_BACCT_OID AND  CAST(A.TCOMITM_CAT_COD AS VARCHAR(10) FOR SBCS DATA)=:TCOMITM_CAT_COD AND  A.RLTD_INSTN_OID=:RLTD_INSTN_OID AND  A.RLTD_CNUM_OID=:RLTD_CNUM_OID AND  A.BLLITM_STOPDT <'9999-12-31' AND  B.BACCT_PARTN_ID=A.BACCT_PARTN_ID AND  B.BLLITM_OID=A.BLLITM_OID AND  B.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM STHDSN1.TICGRP1.RECUR_ITM_HST_DATA WHERE BACCT_PARTN_ID = A.BACCT_PARTN_ID AND BLLITM_OID = A.BLLITM_OID) AND SUBSTR(B.MSG_LINE_TXT,1,250)=:MSG_LINE_TXT ORDER BY 2 DESC, 1, 4",
  "serviceName": "per_avs082_1",
  "description": "per_avs082_1 CURR_BACCT_OID,TCOMITM_CAT_COD,RLTD_INSTN_OID,RLTD_CNUM_OID,MSG_LINE_TXT",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}
