{
  "dburl": "http://131.116.44.152:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":"SELECT A.INTVL_START_DATE, A.INTVL_STOP_DATE, A.ITM_RAT, A.RAT_PRD_INTVL_NM,CAST(A.DB_CRED_IND AS VARCHAR(14) FOR SBCS DATA) AS DB_CRED_IND,CAST(A.RAT_PRD_MESUR_IND AS VARCHAR(14) FOR SBCS DATA) AS RAT_PRD_MESUR_IND,CAST(A.RAT_CHNGE_RSN_TXT AS VARCHAR(14) FOR SBCS DATA) AS RAT_CHNGE_RSN_TXT FROM STHDSN1.TICGRP1.RCUR_ITM_RHST_DATA A WHERE A.BLLITM_OID=:BLLITM_OID AND A.BACCT_PARTN_ID=:BACCT_PARTN_ID ORDER BY A.INTVL_START_DATE DESC",
  "serviceName": "per_reit03",
  "description": "per_reit03 BLLITM_OID,BACCT_PARTN_ID",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}

