--created pps04

SELECT A.INTVL_START_DATE, A.INTVL_STOP_DATE,CAST(B.CNUM_ID AS VARCHAR(14) FOR SBCS DATA) AS CNUM_ID,CAST(A.CNTRB_ELIG_IND AS VARCHAR(14) FOR SBCS DATA) AS CNTRB_ELIG_IND,CAST(A.MAIN_CNTX_VL AS VARCHAR(14) FOR SBCS DATA) AS MAIN_CNTX_VL,CAST(A.OPER_IND AS VARCHAR(14) FOR SBCS DATA) AS OPER_IND FROM STHDSN1.TICGRP1.CNUM_UPPS_DATA A, STHDSN1.TICGRP1.CNUM_ID_HIST_DATA B, STHDSN1.TICGRP1.CUST_ID_HIST_DATA C WHERE CAST( C.CUST_ID  AS VARCHAR(14) FOR SBCS DATA)=:CUST_ID AND A.SBSCT_CUST_OID=C.CUST_OID AND A.SBSCT_ID=:SBSCT_ID AND B.CURR_CUST_PARTN_ID=A.CNUM_CUST_PARTN_ID AND B.CNUM_OID=A.CNUM_OID AND B.INTVL_START_DATE=(SELECT MAX(INTVL_START_DATE) FROM STHDSN1.TICGRP1.CNUM_ID_HIST_DATA WHERE CURR_CUST_PARTN_ID=B.CURR_CUST_PARTN_ID AND CNUM_OID=B.CNUM_OID) ORDER BY B.CNUM_ID ASC




-----Service creation via swagger failed ----


{
  "dburl": "http://131.116.44.152:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.INTVL_START_DATE, A.INTVL_STOP_DATE,CAST(B.CNUM_ID AS VARCHAR(14) FOR SBCS DATA) AS CNUM_ID,CAST(A.CNTRB_ELIG_IND AS VARCHAR(14) FOR SBCS DATA) AS CNTRB_ELIG_IND,CAST(A.MAIN_CNTX_VL AS VARCHAR(14) FOR SBCS DATA) AS MAIN_CNTX_VL,CAST(A.OPER_IND AS VARCHAR(14) FOR SBCS DATA) AS OPER_IND FROM STHDSN1.TICGRP1.CNUM_UPPS_DATA A, STHDSN1.TICGRP1.CNUM_ID_HIST_DATA B, STHDSN1.TICGRP1.CUST_ID_HIST_DATA C WHERE CAST( C.CUST_ID  AS VARCHAR(14) FOR SBCS DATA)=:CUST_ID AND A.SBSCT_CUST_OID=C.CUST_OID AND A.SBSCT_ID=:SBSCT_ID AND B.CURR_CUST_PARTN_ID=A.CNUM_CUST_PARTN_ID AND B.CNUM_OID=A.CNUM_OID AND B.INTVL_START_DATE=(SELECT MAX(INTVL_START_DATE) FROM STHDSN1.TICGRP1.CNUM_ID_HIST_DATA WHERE CURR_CUST_PARTN_ID=B.CURR_CUST_PARTN_ID AND CNUM_OID=B.CNUM_OID) ORDER BY B.CNUM_ID ASC",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "serviceName": "pps04",
  "description": "pps04 based on CUST_ID AND SBSCT_ID",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}


curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/pps04/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq

-----Curl Worked----

curl -X 'POST'  \
'http://131.116.44.152:1317/services/DB2ServiceManager'  \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u cominat5 :INblatS2 \
-d '{
"requestType": "createService",
"sqlStmt": "SELECT A.INTVL_START_DATE, A.INTVL_STOP_DATE,,CAST(B.CNUM_ID AS VARCHAR(14) FOR SBCS DATA) AS CNUM_ID,CAST(A.CNTRB_ELIG_IND AS VARCHAR(14) FOR SBCS DATA) AS CNTRB_ELIG_IND,CAST(A.MAIN_CNTX_VL AS VARCHAR(14) FOR SBCS DATA) AS MAIN_CNTX_VL,CAST(A.OPER_IND AS VARCHAR(14) FOR SBCS DATA) AS OPER_IND FROM STHDSN1.TICGRP1.CNUM_UPPS_DATA A, STHDSN1.TICGRP1.CNUM_ID_HIST_DATA B, STHDSN1.TICGRP1.CUST_ID_HIST_DATA C WHERE CAST( C.CUST_ID  AS VARCHAR(14) FOR SBCS DATA)=:CUST_ID AND A.SBSCT_CUST_OID=C.CUST_OID AND A.SBSCT_ID=:SBSCT_ID AND B.CURR_CUST_PARTN_ID=A.CNUM_CUST_PARTN_ID AND B.CNUM_OID=A.CNUM_OID AND B.INTVL_START_DATE=(SELECT MAX(INTVL_START_DATE) FROM STHDSN1.TICGRP1.CNUM_ID_HIST_DATA WHERE CURR_CUST_PARTN_ID=B.CURR_CUST_PARTN_ID AND CNUM_OID=B.CNUM_OID) ORDER BY B.CNUM_ID ASC",
"collectionID": "SYSIBMSERVICE",
"owner": "COMINAT5",
"validate": "BIND",
"serviceName": "pps04",
"description": "pps04 based on   CUST_ID  AND SBSCT_ID"
}'
----------------------


curl -X 'POST'  \
'http://131.116.44.152:1317/services/DB2ServiceManager'  \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u cominat5 :INblatS2 \
-d '{
"requestType": "createService",
"sqlStmt": "SELECT  A.INTVL_START_DATE  FROM STHDSN1.TICGRP1.CNUM_UPPS_DATA A  WHERE A.SBSCT_CUST_OID=:SBSCT_CUST_OID",
"collectionID": "SYSIBMSERVICE",
"serviceName": "pps04",
"description": "pps04 based on   CUST_ID  AND SBSCT_ID"
}'






