--lns01
SELECT  CHAR(COUNT(*)) FROM    STHDSN1.TICGRP1.CNUM_DATA A, STHDSN1.TICGRP1.CNUM_HIST_DATA B WHERE    ((B.CURR_CUST_PARTN_ID =:CURR_CUST_PARTN_ID AND B.CNUM_OID =:CNUM_OID) OR B.OWN_CNUM_OID =:OWN_CNUM_OID) AND      B.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM STHDSN1.TICGRP1.CNUM_HIST_DATA WHERE CURR_CUST_PARTN_ID = B.CURR_CUST_PARTN_ID AND CNUM_OID = B.CNUM_OID ) AND A.CNUM_OID = B.CNUM_OID AND A.INTVL_STOPDT = '9999-12-31'


{
  "dburl": "http://131.116.44.152:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT  CHAR(COUNT(*)) AS COUNTLINE FROM    STHDSN1.TICGRP1.CNUM_DATA A, STHDSN1.TICGRP1.CNUM_HIST_DATA B WHERE    ((B.CURR_CUST_PARTN_ID =:CURR_CUST_PARTN_ID AND B.CNUM_OID =:CNUM_OID) OR B.OWN_CNUM_OID =:OWN_CNUM_OID) AND      B.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM STHDSN1.TICGRP1.CNUM_HIST_DATA WHERE CURR_CUST_PARTN_ID = B.CURR_CUST_PARTN_ID AND CNUM_OID = B.CNUM_OID ) AND A.CNUM_OID = B.CNUM_OID AND A.INTVL_STOPDT = '9999-12-31'",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "lns01",
  "owner": "COMINAT5",
  "validate": "BIND",
  "description": "lns01 based on CURR_CUST_PARTN_ID and CNUM_OID",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}

60597476--cnumoid
6658509--currcustoid

curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/lns01/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq

curl -X POST \
http://131.116.44.152:1317/services/SYSIBMSERVICE/test01/V1 \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
 "ANSLUTNINGSID": "000000000001558030"
}'