{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":"SELECT DISTINCT 'Per',CASE A.BLLITM_STOPDT WHEN '9999-12-31' THEN 'AK' ELSE 'AN' END,CAST(A.TCOMITM_CAT_COD AS VARCHAR(10) FOR SBCS DATA) AS TCOMITM_CAT_COD,C.CURR_BACCT_ID,CAST(F.CNUM_ID AS VARCHAR(32) FOR SBCS DATA) AS CNUM_ID,A.BLLITM_OID,C.BACCT_OID, A.ASOC_ID,A.RLTD_INSTN_OID, CHAR(A.BLLITM_STOPDT), CHAR(A.BLLITM_STRTDT),C.BACCT_PARTN_ID,A.RLTD_CNUM_OID,SUBSTR(D.MSG_LINE_TXT,1,250),'','','','',1,CAST(A.BLLITM_ID AS VARCHAR(32) FOR SBCS DATA) AS BLLITM_ID FROM STHDSN6.TENGRA2.RECUR_ITEM_DATA A, STHDSN6.TENGRA2.RCUR_ITM_AHST_DATA B, STHDSN6.TENGRA2.RECUR_ITM_HST_DATA D, STHDSN6.TENGRA2.BACCT_DATA C, STHDSN6.TENGRA2.CNUM_ID_HIST_DATA F WHERE B.BACCT_PARTN_ID=:BACCT_PARTN_ID AND B.BACCT_OID=:BACCT_OID AND CAST(F.CNUM_ID AS VARCHAR(32) FOR SBCS DATA) IN (:CNUM_ID,:SUBCNUM_ID) AND F.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM STHDSN6.TENGRA2.CNUM_ID_HIST_DATA WHERE  CURR_CUST_PARTN_ID = F.CURR_CUST_PARTN_ID AND  CNUM_OID = F.CNUM_OID) AND A.BACCT_PARTN_ID = B.CURR_BCT_PARTN_ID AND  A.BLLITM_OID = B.BLLITM_OID AND  A.RLTD_CUST_PARTN_ID = F.CURR_CUST_PARTN_ID AND  A.RLTD_CNUM_OID = F.CNUM_OID AND D.BACCT_PARTN_ID =A.BACCT_PARTN_ID AND  D.BLLITM_OID = A.BLLITM_OID AND  D.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM STHDSN6.TENGRA2.RECUR_ITM_HST_DATA WHERE BACCT_PARTN_ID = D.BACCT_PARTN_ID AND  BLLITM_OID = D.BLLITM_OID) AND  C.BACCT_PARTN_ID = B.CURR_BCT_PARTN_ID AND  C.BACCT_OID=B.CURR_BACCT_OID UNION ALL SELECT DISTINCT 'Övr',CASE A.ACTV_INACTV_IND WHEN 'A' THEN 'AK' ELSE 'AN' END,CAST(A.TCOMITM_CAT_COD AS VARCHAR(10) FOR SBCS DATA) AS TCOMITM_CAT_COD,C.CURR_BACCT_ID,CAST(F.CNUM_ID AS VARCHAR(32) FOR SBCS DATA) AS CNUM_ID,A.BLLITM_OID,A.BACCT_OID, A.ASOC_ID,A.RLTD_INSTN_OID,'','',C.BACCT_PARTN_ID,A.RLTD_CNUM_OID,SUBSTR(A.MSG_LINE_TXT,1,250),CHAR(A.OOCYC_DATE),CHAR(A.OOCYC_TYP_IND),CHAR(A.EXTRT_DET_DATE), CHAR(A.BLLITM_DATE),2,CAST(A.BLLITM_ID AS VARCHAR(32) FOR SBCS DATA) AS BLLITM_ID FROM STHDSN6.TENGRA2.MISC_BLLITM_DATA A, STHDSN6.TENGRA2.CNUM_ID_HIST_DATA F, STHDSN6.TENGRA2.BACCT_DATA C WHERE CAST(F.CNUM_ID AS VARCHAR(32) FOR SBCS DATA) IN (:CNUM_ID,:SUBCNUM_ID) AND  F.INTVL_START_DATE=(SELECT  MAX(INTVL_START_DATE) FROM STHDSN6.TENGRA2.CNUM_ID_HIST_DATA WHERE CURR_CUST_PARTN_ID=F.CURR_CUST_PARTN_ID AND CNUM_OID=F.CNUM_OID) AND C.BACCT_PARTN_ID=:BACCT_PARTN_ID AND C.BACCT_OID=:BACCT_OID AND A.BACCT_PARTN_ID=C.BACCT_PARTN_ID AND A.BACCT_OID=C.BACCT_OID AND A.RLTD_INSTN_OID=F.CURR_INSTN_OID AND A.RLTD_CNUM_OID=F.CNUM_OID AND A.BLLITM_TYP_IND='M' ORDER BY 2,1 desc,14,19,4,18 desc,5,3,8,10 desc,11,6",
  "serviceName": "fkto_anl_union",
  "description": "fkto_anl_union BACCT_PARTN_ID,BACCT_OID, CNUM_ID OR SUBCNUM_ID",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}

