SELECT        A.BLLITM_STRTDT, A.BLLITM_STOPDT, A.BLLITM_OID, A.BLLITM_ID FROM         STHDSN6.TENGRA2.RECUR_ITEM_DATA A, STHDSN6.TENGRA2.CNUM_DATA B, STHDSN6.TENGRA2.RECUR_ITM_HST_DATA C WHERE         A.CURR_BACCT_OID =:CURR_BACCT_OID AND CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA) =:TCOMITM_CAT_COD AND           A.RLTD_INSTN_OID =:RLTD_INSTN_OID AND           B.CURR_CUST_PARTN_ID = A.RLTD_CUST_PARTN_ID AND           B.CNUM_OID = A.RLTD_CNUM_OID AND           C.BACCT_PARTN_ID = A.BACCT_PARTN_ID AND           C.BLLITM_OID = A.BLLITM_OID AND           C.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM   STHDSN6.TENGRA2.RECUR_ITM_HST_DATA WHERE   BACCT_PARTN_ID = A.BACCT_PARTN_ID AND     BLLITM_OID = A.BLLITM_OID) AND           B.CURR_CNUM_ID =:CURR_CNUM_ID AND           A.BLLITM_STOPDT = '9999-12-31' AND      SUBSTR(C.MSG_LINE_TXT,1,250) =:MSG_LINE_TXT ORDER BY 2 DESC, 1, 4



{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":"SELECT        A.BLLITM_STRTDT, A.BLLITM_STOPDT, A.BLLITM_OID, A.BLLITM_ID FROM         STHDSN6.TENGRA2.RECUR_ITEM_DATA A, STHDSN6.TENGRA2.CNUM_DATA B, STHDSN6.TENGRA2.RECUR_ITM_HST_DATA C WHERE         A.CURR_BACCT_OID =:CURR_BACCT_OID AND CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA) =:TCOMITM_CAT_COD AND           A.RLTD_INSTN_OID =:RLTD_INSTN_OID AND           B.CURR_CUST_PARTN_ID = A.RLTD_CUST_PARTN_ID AND           B.CNUM_OID = A.RLTD_CNUM_OID AND           C.BACCT_PARTN_ID = A.BACCT_PARTN_ID AND           C.BLLITM_OID = A.BLLITM_OID AND           C.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM   STHDSN6.TENGRA2.RECUR_ITM_HST_DATA WHERE   BACCT_PARTN_ID = A.BACCT_PARTN_ID AND     BLLITM_OID = A.BLLITM_OID) AND           B.CURR_CNUM_ID =:CURR_CNUM_ID AND           A.BLLITM_STOPDT = '9999-12-31' AND      SUBSTR(C.MSG_LINE_TXT,1,250) =:MSG_LINE_TXT ORDER BY 2 DESC, 1, 4",
  "serviceName": "per_avs081_1",
  "description": "per_avs081_1 based on RLTD_INSTN_OID,CURR_BACCT_OID ,TCOMITM_CAT_COD,CURR_CNUM_ID ,MSG_LINE_TXT",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}


curl -X GET http://131.116.44.144:1316/services/SYSIBMSERVICE/res_avs085/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq