--res_avs085 
SELECT A.BLLITM_DATE, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(50) FOR SBCS DATA) AS BLLITM_ID, A.ACTV_INACTV_IND  FROM STHDSN6.TENGRA2.MISC_BLLITM_DATA A WHERE A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND A.BACCT_OID =:BACCT_OID AND CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA) = :TCOMITM_CAT_COD AND A.BLLITM_TYP_IND = 'F' ORDER BY 4,1 desc   


{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "requestType": "createService",
  "sqlStmt":"SELECT A.BLLITM_DATE, A.BLLITM_OID,CAST(A.BLLITM_ID AS VARCHAR(50) FOR SBCS DATA) AS BLLITM_ID, A.ACTV_INACTV_IND  FROM STHDSN6.TENGRA2.MISC_BLLITM_DATA A WHERE A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND A.BACCT_OID =:BACCT_OID AND CAST(A.TCOMITM_CAT_COD AS VARCHAR(14) FOR SBCS DATA) = :TCOMITM_CAT_COD AND A.BLLITM_TYP_IND = 'F' ORDER BY 4,1 desc ",
  "serviceName": "res_avs085",
  "description": "res_avs085 based on BACCT_PARTN_ID,BACCT_OID ,TCOMITM_CAT_COD",
  "collectionID": "SYSIBMSERVICE",
  "owner": "COMINAT5",
  "validate": "BIND",
  "version": "V1",
  "response": ""
}


curl -X GET http://131.116.44.144:1316/services/SYSIBMSERVICE/res_avs085/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq