--kat001 

SELECT  A.INTVL_START_DATE,A.INTVL_STOP_DATE,CAST(A.SEL_CAT_COD AS VARCHAR(14) FOR SBCS DATA) AS SEL_CAT_COD FROM    STHDSN5.ITSACC.SLCT_CAT_DATA A, STHDSN5.ITSACC.CUST_ID_HIST_DATA B WHERE    CAST( B.CUST_ID  AS VARCHAR(14) FOR SBCS DATA)=:CUST_ID AND     A.CUST_PARTN_ID=B.CUST_PARTN_ID AND     A.SBSCT_CUST_OID= B.CUST_OID ORDER BY INTVL_START_DATE DESC


{
  "dburl": "http://131.116.44.144:1315/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT  A.INTVL_START_DATE,A.INTVL_STOP_DATE,CAST(A.SEL_CAT_COD AS VARCHAR(14) FOR SBCS DATA) AS SEL_CAT_COD FROM    STHDSN5.ITSACC.SLCT_CAT_DATA A, STHDSN5.ITSACC.CUST_ID_HIST_DATA B WHERE    CAST( B.CUST_ID  AS VARCHAR(14) FOR SBCS DATA)=:CUST_ID AND     A.CUST_PARTN_ID=B.CUST_PARTN_ID AND     A.SBSCT_CUST_OID= B.CUST_OID ORDER BY INTVL_START_DATE DESC",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "kat001",
  "owner": "COMINAT5",
  "validate": "BIND",
  "description": "kat001 based on CUST_ID",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}
--55WVYY4309


curl -X GET http://131.116.44.144:1315/services/SYSIBMSERVICE/kat001/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq



