SELECT A.INTVL_START_DATE, A.CUST_PARTN_ID, A.CUST_OID,CAST(A.MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA) AS MLDST_TYPCD, A.MLDST_ID FROM   STHDSN6.TENGRA2.MAIL_DEST_DATA A, STHDSN6.TENGRA2.BILL_PRDRL_DATA B WHERE  B.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    B.BACCT_OID =:BACCT_OID AND    B.PRIM_IND =:PRIM_IND AND    B.BILL_RUN_TYP_IND =:BILL_RUN_TYP_IND AND    B.BILL_PROD_RULE_ID =:BILL_PROD_RULE_ID AND    B.INTVL_START_DATE =:INTVL_START_DATE AND    A.CUST_PARTN_ID = B.MLDST_CST_PARTN_ID AND    A.CUST_OID = B.MLDST_CUST_OID AND    A.MLDST_TYPCD = B.MLDST_TYPCD AND    A.MLDST_ID = B.MLDST_ID ORDER BY 1 DESC



{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.INTVL_START_DATE, A.CUST_PARTN_ID, A.CUST_OID,CAST(A.MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA) AS MLDST_TYPCD, A.MLDST_ID FROM   STHDSN6.TENGRA2.MAIL_DEST_DATA A, STHDSN6.TENGRA2.BILL_PRDRL_DATA B WHERE  B.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    B.BACCT_OID =:BACCT_OID AND    B.PRIM_IND =:PRIM_IND AND    B.BILL_RUN_TYP_IND =:BILL_RUN_TYP_IND AND    B.BILL_PROD_RULE_ID =:BILL_PROD_RULE_ID AND    B.INTVL_START_DATE =:INTVL_START_DATE AND    A.CUST_PARTN_ID = B.MLDST_CST_PARTN_ID AND    A.CUST_OID = B.MLDST_CUST_OID AND    A.MLDST_TYPCD = B.MLDST_TYPCD AND    A.MLDST_ID = B.MLDST_ID ORDER BY 1 DESC",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "prrads03",
  "owner": "COMINAT5",
   "validate": "BIND",
  "description": "prrads03 based on BACCT_PARTN_ID,BACCT_OID ,PRIM_IND,BILL_RUN_TYP_IND,BILL_PROD_RULE_ID and INTVL_START_DATE ",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}
curl -X GET http://131.116.44.144:1316/services/SYSIBMSERVICE/prrads03/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq


