--fks04

SELECT A.EFFEC_START_DATE, A.LAST_BILL_DATE, A.EFFEC_STOP_DATE, A.FINAL_BILL_DATE, CAST(A.BILL_STATUS_IND AS VARCHAR(14) FOR SBCS DATA) AS BILL_STATUS_IND, A.CRED_LIM_AMT, A.INV_SUMM_IND, A.BORGN_IND, A.DEPOS_IND, C.NXT_PREDC_RUN_DATE, C.RUN_DATE, C.BILL_DATE, C.BCYCL_INPRG_IND, C.BCYCL_COD FROM  STHDSN6.TENGRA2.BACCT_DATA A, STHDSN6.TENGRA2.BCYCL_CNTL_TABL C WHERE  A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    A.BACCT_OID =:BACCT_OID AND    C.BCYCL_COD = A.BACCT_CYCLE_ID




	{
	  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
	  "username": "a472inb",
	  "password": "INblatS2",
	  "sqlStmt": "SELECT A.EFFEC_START_DATE, A.LAST_BILL_DATE, A.EFFEC_STOP_DATE, A.FINAL_BILL_DATE, CAST(A.BILL_STATUS_IND AS VARCHAR(14) FOR SBCS DATA) AS BILL_STATUS_IND, A.CRED_LIM_AMT, A.INV_SUMM_IND, A.BORGN_IND, A.DEPOS_IND, C.NXT_PREDC_RUN_DATE, C.RUN_DATE, C.BILL_DATE, C.BCYCL_INPRG_IND, C.BCYCL_COD FROM  STHDSN6.TENGRA2.BACCT_DATA A, STHDSN6.TENGRA2.BCYCL_CNTL_TABL C WHERE  A.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    A.BACCT_OID =:BACCT_OID AND    C.BCYCL_COD = A.BACCT_CYCLE_ID",

	  "collectionID": "SYSIBMSERVICE",
	  "serviceName": "fks04",
	  "owner": "COMINAT5",
	  "validate": "BIND",
	  "description": "fks04 based on BACCT_PARTN_ID ,BACCT_OID ",
	  "requestType": "createService",
	  "version": "V1",
	  "response": ""
	}



curl -X GET http://131.116.44.144:1316/services/SYSIBMSERVICE/fks04/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq

