--fks031

SELECT A.CURR_BACCT_ID, A.BACCT_OID, A.BACCT_PARTN_ID FROM  STHDSN5.ITSACC.BACCT_DATA A , STHDSN5.ITSACC.BACCT_HIST_DATA B WHERE  B.CUST_OID =:CUST_OID AND    B.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM  STHDSN5.ITSACC.BACCT_HIST_DATA WHERE  BACCT_PARTN_ID = B.BACCT_PARTN_ID AND    BACCT_OID = B.BACCT_OID) AND    A.BACCT_PARTN_ID = B.BACCT_PARTN_ID AND    A.BACCT_OID = B.BACCT_OID AND    B.BACCT_OID =:BACCT_OID AND    B.BACCT_PARTN_ID =:BACCT_PARTN_ID ORDER BY A.CURR_BACCT_ID ASC





{
  "dburl": "http://131.116.44.144:1315/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.CURR_BACCT_ID, A.BACCT_OID, A.BACCT_PARTN_ID FROM  STHDSN5.ITSACC.BACCT_DATA A , STHDSN5.ITSACC.BACCT_HIST_DATA B WHERE  B.CUST_OID =:CUST_OID AND    B.INTVL_START_DATE = (SELECT MAX(INTVL_START_DATE) FROM  STHDSN5.ITSACC.BACCT_HIST_DATA WHERE  BACCT_PARTN_ID = B.BACCT_PARTN_ID AND    BACCT_OID = B.BACCT_OID) AND    A.BACCT_PARTN_ID = B.BACCT_PARTN_ID AND    A.BACCT_OID = B.BACCT_OID AND    B.BACCT_OID =:BACCT_OID AND    B.BACCT_PARTN_ID =:BACCT_PARTN_ID ORDER BY A.CURR_BACCT_ID ASC",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "fks031",
  "owner": "COMINAT5",
  "validate": "BIND",
  "description": "fks031 based on  CUST_OID,BACCT_OID and BACCT_PARTN_ID",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}

60597476--cnumoid
6658509--currcustoid

curl -X GET http://131.116.44.144:1315/services/SYSIBMSERVICE/fks031/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq

