SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.TCOMITM_CAT_COD AS PROMIS, E.BEORDRIN, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM    STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENA2.FPT8200 E WHERE   A.CUST_PARTN_ID=:CUST_PARTN_ID AND     A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND     B.CUST_PARTN_ID=A.CUST_PARTN_ID AND     A.AGREE_OID=B.AGREE_OID AND     D.CUST_PARTN_ID = A.CUST_PARTN_ID AND     D.CUST_OID = A.SBSCT_CUST_OID AND     A.TCOMITM_CAT_COD <> '' AND DECIMAL(A.TCOMITM_CAT_COD) = E.PROMIS_ID --working


UNION SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.TCOMITM_CAT_COD AS PROMIS, 'SAKNAS/AVVECKLAD', A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D WHERE   A.CUST_PARTN_ID=:CUST_PARTN_ID AND A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND     B.CUST_PARTN_ID=A.CUST_PARTN_ID AND     A.AGREE_OID=B.AGREE_OID AND     D.CUST_PARTN_ID = A.CUST_PARTN_ID AND     D.CUST_OID = A.SBSCT_CUST_OID AND A.TCOMITM_CAT_COD NOT EQUAL '' AND NOT EXISTS (SELECT * FROM STHDSN6.TENA2.FPT8200 E WHERE DECIMAL(A.TCOMITM_CAT_COD) = E.PROMIS_ID) UNION  --not working -Query1




SELECT  A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, E.BEORDRIN, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM    STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENA2.FPT8200 E WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND      A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND      B.CUST_PARTN_ID=A.CUST_PARTN_ID AND      A.AGREE_OID=B.AGREE_OID AND      A.TCOMITM_CAT_COD = '' AND      D.CUST_PARTN_ID = A.CUST_PARTN_ID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      D.CUST_OID = A.SBSCT_CUST_OID AND DECIMAL(A.ASOC_ID) = E.PROMIS_ID -- working

UNION SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, E.TRT_VL, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM     STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENGRA2.ASGND_TRT_TABL E WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND      A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND      B.CUST_PARTN_ID=A.CUST_PARTN_ID AND      A.AGREE_OID=B.AGREE_OID AND      A.TCOMITM_CAT_COD = '' AND      D.CUST_PARTN_ID = A.CUST_PARTN_ID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      A.ASOC_ID = E.ASOC_ID -- working 


UNION SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, 'SAKNAS/AVVECKLAD', A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM     STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND      A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND      B.CUST_PARTN_ID=A.CUST_PARTN_ID AND      A.AGREE_OID=B.AGREE_OID AND      A.TCOMITM_CAT_COD = '' AND      D.CUST_PARTN_ID = A.CUST_PARTN_ID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      NOT EXISTS (SELECT * FROM STHDSN6.TENA2.FPT8200 E WHERE DECIMAL(A.ASOC_ID) = E.PROMIS_ID) AND      NOT EXISTS (SELECT * FROM STHDSN6.TENGRA2.ASGND_TRT_TABL F WHERE A.ASOC_ID = F.ASOC_ID) ORDER BY  1--working

--------------------------------

optimised Query1----------------------------------

SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.TCOMITM_CAT_COD AS PROMIS, E.BEORDRIN, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM    STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENA2.FPT8200 E WHERE   A.CUST_PARTN_ID=:CUST_PARTN_ID AND     A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND     A.TCOMITM_CAT_COD <> '' AND     B.CUST_PARTN_ID=A.CUST_PARTN_ID AND     B.AGREE_OID=A.AGREE_OID AND     D.CUST_PARTN_ID = A.CUST_PARTN_ID AND     D.CUST_OID = A.SBSCT_CUST_OID AND     E.PROMIS_ID = DECIMAL(A.TCOMITM_CAT_COD) --not working
UNION SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.TCOMITM_CAT_COD AS PROMIS, 'SAKNAS/AVVECKLAD', A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM    STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D WHERE   A.CUST_PARTN_ID=:CUST_PARTN_ID AND     A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND     A.TCOMITM_CAT_COD <> '' AND     B.CUST_PARTN_ID=A.CUST_PARTN_ID AND     B.AGREE_OID=A.AGREE_OID AND     D.CUST_PARTN_ID = A.CUST_PARTN_ID AND     D.CUST_OID = A.SBSCT_CUST_OID AND     NOT EXISTS (SELECT E.PROMIS_ID FROM STHDSN6.TENA2.FPT8200 E WHERE  E.PROMIS_ID = DECIMAL(A.TCOMITM_CAT_COD))

 UNION SELECT  A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, E.BEORDRIN, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM    STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENA2.FPT8200 E WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND      A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND      A.TCOMITM_CAT_COD = '' AND      B.CUST_PARTN_ID=A.CUST_PARTN_ID AND      B.AGREE_OID=A.AGREE_OID AND      D.CUST_PARTN_ID = A.CUST_PARTN_ID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      E.PROMIS_ID = DECIMAL(A.ASOC_ID) 
 
 UNION SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, E.TRT_VL, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM     STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENGRA2.ASGND_TRT_TABL E WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND      A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND      A.TCOMITM_CAT_COD = '' AND      B.CUST_PARTN_ID=A.CUST_PARTN_ID AND      B.AGREE_OID=A.AGREE_OID AND      D.CUST_PARTN_ID = A.CUST_PARTN_ID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      E.ASOC_ID = A.ASOC_ID


 UNION SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, 'SAKNAS/AVVECKLAD', A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND A.TCOMITM_CAT_COD = '' AND B.CUST_PARTN_ID=A.CUST_PARTN_ID AND B.AGREE_OID=A.AGREE_OID AND D.CUST_PARTN_ID = A.CUST_PARTN_ID AND D.CUST_OID = A.SBSCT_CUST_OID AND NOT EXISTS (SELECT E.PROMIS_ID FROM STHDSN6.TENA2.FPT8200 E WHERE  E.PROMIS_ID = DECIMAL(A.ASOC_ID)) AND NOT EXISTS (SELECT F.ASOC_ID FROM STHDSN6.TENGRA2.ASGND_TRT_TABL F WHERE F.ASOC_ID = A.ASOC_ID) ORDER BY  1 

----




{
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.ASOC_ID AS PROMIS, E.TRT_VL, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM     STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENGRA2.ASGND_TRT_TABL E WHERE    A.CUST_PARTN_ID=:CUST_PARTN_ID AND      A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND      A.TCOMITM_CAT_COD = '' AND      B.CUST_PARTN_ID=A.CUST_PARTN_ID AND      B.AGREE_OID=A.AGREE_OID AND      D.CUST_PARTN_ID = A.CUST_PARTN_ID AND      D.CUST_OID = A.SBSCT_CUST_OID AND      E.ASOC_ID = A.ASOC_ID",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "pps01",
  "description": "pps01 based on CUST_ID AND SBSCT_ID",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}


 {
  "dburl": "http://131.116.44.144:1316/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "pps01",
  "requestType": "dropService",
  "version": "V1",
  "response": ""
}
----------------------------


curl -X 'POST'  \
'http://131.116.44.144:1316/services/DB2ServiceManager'  \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
"requestType": "createService",
"sqlStmt": "SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.TCOMITM_CAT_COD AS PROMIS, E.BEORDRIN, A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM    STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D, STHDSN6.TENA2.FPT8200 E WHERE   A.CUST_PARTN_ID=:CUST_PARTN_ID AND     A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND     A.TCOMITM_CAT_COD <> '' AND     B.CUST_PARTN_ID=A.CUST_PARTN_ID AND     B.AGREE_OID=A.AGREE_OID AND     D.CUST_PARTN_ID = A.CUST_PARTN_ID AND     D.CUST_OID = A.SBSCT_CUST_OID AND     E.PROMIS_ID = DECIMAL(A.TCOMITM_CAT_COD)",
"collectionID": "SYSIBMSERVICE",
"serviceName": "PPS01",
"description": "PPS01 based on   CUST_PARTN_ID  AND SBSCT_CUST_OID"
}'


{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-199 SQLSTATE=42601 TOKENS=B�AND * AT OR SELECTIVITY YEAR YEARS MONTH MONTHS DAY DAYS HOUR CSECT NAME=DSNHPARS  RDS CODE=2 . Error Location:DSNLJMUS:160"}[appadmin@ib009inblicwwwt ~]$
{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-199 SQLSTATE=42601 TOKENS=B�AND * AT OR SELECTIVITY YEAR YEARS MONTH MONTHS DAY DAYS HOUR CSECT NAME=DSNHPARS  RDS CODE=2 . Error Location:DSNLJMUS:160"}[appadmin@ib009inblicwwwt ~]$
{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-199 SQLSTATE=42601 TOKENS=B�AND * AT OR SELECTIVITY YEAR YEARS MONTH MONTHS DAY DAYS HOUR CSECT NAME=DSNHPARS  RDS CODE=2 . Error Location:DSNLJMUS:160"}[appadmin@ib009inblicwwwt ~]$ ^C
{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-199 SQLSTATE=42601 TOKENS=B�AND * AT OR SELECTIVITY YEAR YEARS MONTH MONTHS DAY DAYS HOUR CSECT NAME=DSNHPARS  RDS CODE=2 . Error Location:DSNLJMUS:160"}[appadmin@ib009inblicwwwt ~]$
{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-199 SQLSTATE=42601 TOKENS=B�AND * AT OR SELECTIVITY YEAR YEARS MONTH MONTHS DAY DAYS HOUR CSECT NAME=DSNHPARS  RDS CODE=2 . Error Location:DSNLJMUS:160"}[appadmin@ib009inblicwwwt ~]$


SELECT   A.SBSCT_ID, A.SBSCT_STRTDT, A.SBSCT_STOPDT, A.TCOMITM_CAT_COD AS PROMIS, 'SAKNAS/AVVECKLAD', A.GRP_TYPIND, A.UPP_PLAN_TYP_IND, A.RPROC_IND, A.BOUTPT_LOC_IND, A.INSTN_OID, B.AGREE_ID, D.PRSON_ORG_NM, D.CURR_CUST_ID FROM STHDSN6.TENGRA2.USAG_PPSCPTN_DATA A, STHDSN6.TENGRA2.AGREEMENT_DATA B, STHDSN6.TENGRA2.CUSTOMER_DATA D WHERE   A.CUST_PARTN_ID=:CUST_PARTN_ID AND A.SBSCT_CUST_OID=:SBSCT_CUST_OID AND     B.CUST_PARTN_ID=A.CUST_PARTN_ID AND     A.AGREE_OID=B.AGREE_OID AND     D.CUST_PARTN_ID = A.CUST_PARTN_ID AND     D.CUST_OID = A.SBSCT_CUST_OID AND A.TCOMITM_CAT_COD NOT EQUAL '' AND NOT EXISTS (SELECT E.PROMIS_ID FROM STHDSN6.TENA2.FPT8200 E WHERE E.PROMIS_ID=DECIMAL(A.TCOMITM_CAT_COD))

NOT EXISTS (SELECT E.PROMIS_ID FROM STHDSN6.TENA2.FPT8200 E WHERE E.PROMIS_ID=DECIMAL(A.TCOMITM_CAT_COD))

Error--{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-104 SQLSTATE=42601 TOKENS=EQUAL�IN  CSECT NAME=DSNHPARS  RDS CODE=3 . Error Location:DSNLJMUS:160"}[appadmin@ib009inblicwwwt ~]$

Error--{"StatusCode":500,"StatusDescription":"create failed for SYSIBMSERVICE.PPS01.(V1) due to DSNX200I  * BIND SQL ERROR  USING A472INB AUTHORITY  PLAN=(NOT APPLICABLE)  DBRM=PPS01 STATEMENT=0  SQLCODE=-104 SQLSTATE=42601 TOKENS=D�AND * AT OR SELECTIVITY YEAR YEARS MONTH MONTHS DAY DAYS HOUR CSECT NAME=DSNHPARS  RDS CODE=3 . Error Location:DSNLJMUS:160"}


