--prrads02 
SELECT INTVL_STOP_DATE, ADDR_ID,CAST(CARE_OF_NAME AS VARCHAR(55) FOR SBCS DATA) AS CARE_OF_NAME,CAST(RCPNT_NAME AS VARCHAR(55) FOR SBCS DATA) AS RCPNT_NAME,CAST(LINE_1_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_1_ADDR,CAST(LINE_2_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_2_ADDR,CAST(LINE_3_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_3_ADDR,CAST(LINE_4_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_4_ADDR,CAST(MLDST_TYPCD AS VARCHAR(55) FOR SBCS DATA) AS MLDST_TYPCD FROM   STHDSN1.TICGRP1.MAIL_DEST_DATA  WHERE INTVL_START_DATE =:INTVL_START_DATE AND  CAST(MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA)   =:MLDST_TYPCD AND    MLDST_ID =:MLDST_ID AND    CUST_OID =:CUST_OID AND    CUST_PARTN_ID =:CUST_PARTN_ID



{
  "dburl": "http://131.116.44.150:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT INTVL_STOP_DATE, ADDR_ID,CAST(CARE_OF_NAME AS VARCHAR(55) FOR SBCS DATA) AS CARE_OF_NAME,CAST(RCPNT_NAME AS VARCHAR(55) FOR SBCS DATA) AS RCPNT_NAME,CAST(LINE_1_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_1_ADDR,CAST(LINE_2_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_2_ADDR,CAST(LINE_3_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_3_ADDR,CAST(LINE_4_ADDR AS VARCHAR(55) FOR SBCS DATA) AS LINE_4_ADDR,CAST(MLDST_TYPCD AS VARCHAR(55) FOR SBCS DATA) AS MLDST_TYPCD FROM   STHDSN1.TICGRP1.MAIL_DEST_DATA  WHERE INTVL_START_DATE =:INTVL_START_DATE AND  CAST(MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA)   =:MLDST_TYPCD AND    MLDST_ID =:MLDST_ID AND    CUST_OID =:CUST_OID AND    CUST_PARTN_ID =:CUST_PARTN_ID",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "prrads02",
  "owner": "COMINAT5",
   "validate": "BIND",
  "description": "prrads02 based on INTVL_START_DATE,MLDST_TYPCD ,MLDST_ID,CUST_OID and CUST_PARTN_ID ",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}
curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/prrads02/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq

