SELECT A.INTVL_START_DATE, A.CUST_PARTN_ID, A.CUST_OID,CAST(A.MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA) AS MLDST_TYPCD, A.MLDST_ID FROM   STHDSN1.TICGRP1.MAIL_DEST_DATA A, STHDSN1.TICGRP1.BILL_PRDRL_DATA B WHERE  B.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    B.BACCT_OID =:BACCT_OID AND     CAST(B.PRIM_IND AS VARCHAR(14) FOR SBCS DATA)=:PRIM_IND AND   CAST(B.BILL_RUN_TYP_IND AS VARCHAR(14) FOR SBCS DATA)=:BILL_RUN_TYP_IND AND   CAST(B.BILL_PROD_RULE_ID AS VARCHAR(14) FOR SBCS DATA)=:BILL_PROD_RULE_ID AND    B.INTVL_START_DATE =:INTVL_START_DATE AND    A.CUST_PARTN_ID = B.MLDST_CST_PARTN_ID AND    A.CUST_OID = B.MLDST_CUST_OID AND    A.MLDST_TYPCD = B.MLDST_TYPCD AND    A.MLDST_ID = B.MLDST_ID ORDER BY 1 DESC


curl -X 'POST'  \
'http://131.116.44.150:1317/services/DB2ServiceManager'  \
-H 'accept: application/json'   \
-H 'Content-Type: application/json' \
-u a472inb:INblatS2 \
-d '{
"requestType": "createService",
"sqlStmt": "SELECT A.INTVL_START_DATE, A.CUST_PARTN_ID, A.CUST_OID,CAST(A.MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA) AS MLDST_TYPCD, A.MLDST_ID FROM   STHDSN1.TICGRP1.MAIL_DEST_DATA A, STHDSN1.TICGRP1.BILL_PRDRL_DATA B WHERE  B.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    B.BACCT_OID =:BACCT_OID AND     CAST(B.PRIM_IND AS VARCHAR(14) FOR SBCS DATA)=:PRIM_IND AND   CAST(B.BILL_RUN_TYP_IND AS VARCHAR(14) FOR SBCS DATA)=:BILL_RUN_TYP_IND AND   CAST(B.BILL_PROD_RULE_ID AS VARCHAR(14) FOR SBCS DATA)=:BILL_PROD_RULE_ID AND    B.INTVL_START_DATE =:INTVL_START_DATE AND    A.CUST_PARTN_ID = B.MLDST_CST_PARTN_ID AND    A.CUST_OID = B.MLDST_CUST_OID AND    A.MLDST_TYPCD = B.MLDST_TYPCD AND    A.MLDST_ID = B.MLDST_ID ORDER BY 1 DESC",
"serviceName": "prrads03",
  "OWNER": "COMINAT5",
    "collectionID": "SYSIBMSERVICE",
  "VALIDATE": "BIND",
"description": "prrads03 based on BACCT_PARTN_ID,BACCT_OID ,PRIM_IND,BILL_RUN_TYP_IND,BILL_PROD_RULE_ID and INTVL_START_DATE"
}'

{
  "dburl": "http://131.116.44.150:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT A.INTVL_START_DATE, A.CUST_PARTN_ID, A.CUST_OID,CAST(A.MLDST_TYPCD AS VARCHAR(14) FOR SBCS DATA) AS MLDST_TYPCD, A.MLDST_ID FROM   STHDSN1.TICGRP1.MAIL_DEST_DATA A, STHDSN1.TICGRP1.BILL_PRDRL_DATA B WHERE  B.BACCT_PARTN_ID =:BACCT_PARTN_ID AND    B.BACCT_OID =:BACCT_OID AND     CAST(B.PRIM_IND AS VARCHAR(14) FOR SBCS DATA) =:PRIM_IND AND   CAST(B.BILL_RUN_TYP_IND AS VARCHAR(14) FOR SBCS DATA)  =:BILL_RUN_TYP_IND AND   CAST(B.BILL_PROD_RULE_ID AS VARCHAR(14) FOR SBCS DATA)  =:BILL_PROD_RULE_ID AND    B.INTVL_START_DATE =:INTVL_START_DATE AND    A.CUST_PARTN_ID = B.MLDST_CST_PARTN_ID AND    A.CUST_OID = B.MLDST_CUST_OID AND    A.MLDST_TYPCD = B.MLDST_TYPCD AND    A.MLDST_ID = B.MLDST_ID ORDER BY 1 DESC",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "prrads03",
  "owner": "COMINAT5",
   "validate": "BIND",
  "description": "prrads03 based on BACCT_PARTN_ID,BACCT_OID ,PRIM_IND,BILL_RUN_TYP_IND,BILL_PROD_RULE_ID and INTVL_START_DATE ",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}
curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/prrads03/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq


