SELECT  INTVL_START_DATE,  CAST(SPFNRL_ID AS VARCHAR(14) FOR SBCS DATA) As SPFNRL_ID, SPFNRL_CMPNT_SQNM, SPCFN_ENT_IND, SPCFN_ENT_OID, RLTD_CNUM_OID, RLTD_CUST_PARTN_ID, RLTD_INSLC_OID, RLTD_CNUM_GRP_OID,  CAST(RULE_USE_IND AS VARCHAR(14) FOR SBCS DATA) AS RULE_USE_IND, DEST_VL_LEN, INTVL_STOP_DATE, CAST(CUST_REF_NM AS VARCHAR(14) FOR SBCS DATA) AS CUST_REF_NM,CAST(DEST_BEGIN_VL AS VARCHAR(14) FOR SBCS DATA) AS  DEST_BEGIN_VL, CAST(DEST_END_VL AS VARCHAR(14) FOR SBCS DATA) AS DEST_END_VL,CAST(USAG_CLSFN_COD AS VARCHAR(14) FOR SBCS DATA) AS USAG_CLSFN_COD, CAST(PRICE_PLAN_ID AS VARCHAR(14) FOR SBCS DATA) AS PRICE_PLAN_ID, ONE_LINE_USAG_IND FROM    STHDSN1.TICGRP1.SPCFN_RULE_DATA WHERE   BACCT_PARTN_ID=:BACCT_PARTN_ID AND     BACCT_OID=:BACCT_OID AND    CAST(SPFNRL_ID AS VARCHAR(14) FOR SBCS DATA) =:SPFNRL_ID ORDER BY INTVL_START_DATE DESC, SPFNRL_CMPNT_SQNM ASC


       
		  
		
{
  "dburl": "http://131.116.44.150:1317/services/DB2ServiceManager",
  "username": "a472inb",
  "password": "INblatS2",
  "sqlStmt": "SELECT  INTVL_START_DATE,  CAST(SPFNRL_ID AS VARCHAR(14) FOR SBCS DATA) As SPFNRL_ID, SPFNRL_CMPNT_SQNM, SPCFN_ENT_IND, SPCFN_ENT_OID, RLTD_CNUM_OID, RLTD_CUST_PARTN_ID, RLTD_INSLC_OID, RLTD_CNUM_GRP_OID,  CAST(RULE_USE_IND AS VARCHAR(14) FOR SBCS DATA) AS RULE_USE_IND, DEST_VL_LEN, INTVL_STOP_DATE, CAST(CUST_REF_NM AS VARCHAR(14) FOR SBCS DATA) AS CUST_REF_NM,CAST(DEST_BEGIN_VL AS VARCHAR(14) FOR SBCS DATA) AS  DEST_BEGIN_VL, CAST(DEST_END_VL AS VARCHAR(14) FOR SBCS DATA) AS DEST_END_VL,CAST(USAG_CLSFN_COD AS VARCHAR(14) FOR SBCS DATA) AS USAG_CLSFN_COD, CAST(PRICE_PLAN_ID AS VARCHAR(14) FOR SBCS DATA) AS PRICE_PLAN_ID, ONE_LINE_USAG_IND FROM    STHDSN1.TICGRP1.SPCFN_RULE_DATA WHERE   BACCT_PARTN_ID=:BACCT_PARTN_ID AND     BACCT_OID=:BACCT_OID AND    CAST(SPFNRL_ID AS VARCHAR(14) FOR SBCS DATA) =:SPFNRL_ID ORDER BY INTVL_START_DATE DESC, SPFNRL_CMPNT_SQNM ASC",
  "collectionID": "SYSIBMSERVICE",
  "serviceName": "sps01",
  "owner": "COMINAT5",
   "validate": "BIND",
  "description": "sps01 based on BACCT_PARTN_ID,BACCT_OID and SPFNRL_ID ",
  "requestType": "createService",
  "version": "V1",
  "response": ""
}
curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/sps01/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq



curl -X GET http://131.116.44.152:1317/services/SYSIBMSERVICE/sps01/V1 -H "Content-Type: application/json" -u a472inb:INblatS2 | jq



